### Numpy

#### first of all, let's see the differences between a numpy array and a list:

In [1]:
import numpy as np

In [4]:
myarray = np.array([3.14,44,44.5,2.18])

In [10]:
myarray

array([ 3.14, 44.  , 44.5 ,  2.18])

In [7]:
type(myarray)

numpy.ndarray

In [8]:
mylist = [3.14,44,44.5,2.18]

In [11]:
mylist

[3.14, 44, 44.5, 2.18]

In [9]:
type(mylist)

list

In [12]:
result1 = myarray*10

In [14]:
result1

array([ 31.4, 440. , 445. ,  21.8])

In [13]:
result2 = mylist*10

In [16]:
print(result2)

[3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18]


In [18]:
mat1 = np.matrix([[1,2],[3,4]])

In [19]:
mat1*mat1

matrix([[ 7, 10],
        [15, 22]])