## Numpy

### first of all, let's see the differences between a numpy array and a list:

In [1]:
import numpy as np

In [2]:
myarray = np.array([3.14,44,44.5,2.18])

In [3]:
myarray

array([ 3.14, 44.  , 44.5 ,  2.18])

In [4]:
type(myarray)

numpy.ndarray

In [6]:
mylist = [3.14,44,44.5,2.18]

In [7]:
mylist

[3.14, 44, 44.5, 2.18]

In [8]:
type(mylist)

list

In [9]:
result1 = myarray*10

In [10]:
result1

array([ 31.4, 440. , 445. ,  21.8])

In [11]:
result2 = mylist*10

In [12]:
print(result2)

[3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18, 3.14, 44, 44.5, 2.18]


In [13]:
mat1 = np.matrix([[1,2],[3,4]])

In [14]:
mat1*mat1

matrix([[ 7, 10],
        [15, 22]])

In [15]:
sequence = np.linspace(11,12,100) #This function returns a matrix with evenly spaced values 

In [16]:
sequence

array([11.        , 11.01010101, 11.02020202, 11.03030303, 11.04040404,
       11.05050505, 11.06060606, 11.07070707, 11.08080808, 11.09090909,
       11.1010101 , 11.11111111, 11.12121212, 11.13131313, 11.14141414,
       11.15151515, 11.16161616, 11.17171717, 11.18181818, 11.19191919,
       11.2020202 , 11.21212121, 11.22222222, 11.23232323, 11.24242424,
       11.25252525, 11.26262626, 11.27272727, 11.28282828, 11.29292929,
       11.3030303 , 11.31313131, 11.32323232, 11.33333333, 11.34343434,
       11.35353535, 11.36363636, 11.37373737, 11.38383838, 11.39393939,
       11.4040404 , 11.41414141, 11.42424242, 11.43434343, 11.44444444,
       11.45454545, 11.46464646, 11.47474747, 11.48484848, 11.49494949,
       11.50505051, 11.51515152, 11.52525253, 11.53535354, 11.54545455,
       11.55555556, 11.56565657, 11.57575758, 11.58585859, 11.5959596 ,
       11.60606061, 11.61616162, 11.62626263, 11.63636364, 11.64646465,
       11.65656566, 11.66666667, 11.67676768, 11.68686869, 11.69

###    Basic mathematical operations with numpy array

In [17]:
myarray.max()

44.5

In [18]:
myarray.sum()

93.82000000000001

In [19]:
myarray.mean()

23.455000000000002

In [20]:
myarray.std()

20.798520981069785

In [22]:
dir(myarray) # This function shows us all the resources inside (can be applied) the object between parentheses

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

Operations with Data structures

In [23]:
myvector = np.array([3.14,42,2.718,4])

In [24]:
myvector.size

4

In [25]:
myvector.shape

(4,)

In [26]:
myvector[2]

2.718

In [29]:
np.argwhere(myvector == 2.718)

array([[2]], dtype=int64)

In [32]:
myvector.argmin(), myvector.argmax() # by index

(2, 1)

## Pandas

#### Pandas has two fundamental data structures: Series and Data Frame

In [33]:
import pandas as pd

In [34]:
myserie = pd.Series([3.14,44,44.5,2.18])

In [35]:
myserie

0     3.14
1    44.00
2    44.50
3     2.18
dtype: float64

In [36]:
type(myserie)

pandas.core.series.Series

In [40]:
mydf = pd.DataFrame({
    'Names':['Joseph','Maria','Pedro'],
    'Salary':[100,180,130]
})

In [42]:
print(mydf)

    Names  Salary
0  Joseph     100
1   Maria     180
2   Pedro     130


In [43]:
type(mydf)

pandas.core.frame.DataFrame

#### But what are these two structures made of?

In [44]:
# Showing columns
print(mydf.columns)

Index(['Names', 'Salary'], dtype='object')


In [45]:
# Showing index
print(mydf.index)

RangeIndex(start=0, stop=3, step=1)


In [46]:
# showing data
print(mydf.values)

[['Joseph' 100]
 ['Maria' 180]
 ['Pedro' 130]]


In [54]:
df1 = pd.DataFrame({
    'Column a':[3.14,2.718],
    'Column b':[42,4]
})

In [55]:
df1.columns = ['Factory A','Factory B']

In [58]:
rows = ['Ano 1','Ano 2']
df1.index = rows

In [59]:
df1

TypeError: 'list' object is not callable

TypeError: 'list' object is not callable